spring:
  application:
    name: ws-order
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_local
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ws-order-management
    show-sql: false
  flyway:
    enabled: true
    schemas: ws-order-management
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration
    baseline-version: 1

  cloud:
    config:
      enabled: false

server:
  port: 18763
  servlet:
    encoding:
      force: true
      charset: utf-8